### ISSUE TITLE
Unreachable code in mcrx_subscription_native_join()

### ISSUE THREAD

**Issue by ghenry** [GrumpyOldTroll/libmcrx#13]
https://github.com/GrumpyOldTroll/libmcrx/blob/d178b6c8a99485e4f1224f34cac053ff7397048f/src/native.c#L1283

**Comment by ghenry** [comment]
```
      if (close(sock_fd) < 0) {
        handle_close_error(ctx);
      }
      return MCRX_ERR_UNKNOWN_FAMILY;
```

can be deleted.

**Comment by GrumpyOldTroll** [comment]
I guess the whole default case could be removed since earlier code in the function forces addr_type to one of the handled values.  I think it would probably be a mistake to leave a blank default case here though.

(Was this also from a code coverage warning or something?)

**Comment by ghenry** [comment]
These are all warnings from CLion and/or cppcheck/others. Static analysis
real time.
