### ISSUE TITLE
Unreachable code in mcrx_prv_remove_socket_cb()

### ISSUE THREAD

**Issue by ghenry** [GrumpyOldTroll/libmcrx#14]
https://github.com/GrumpyOldTroll/libmcrx/blob/d178b6c8a99485e4f1224f34cac053ff7397048f/src/wait.c#L653

**Comment by GrumpyOldTroll** [comment]
Now that I got a chance to look at this, I'm pretty sure this code is missing a check in this loop looking something like:

~~~
    if (cur_cb->fd != fd) {
      continue;
    }
~~~

Not sure what you mean bby "unreachable" tho, is that results from a coverage run or static analysis or what?

**Comment by ghenry** [comment]
It just means it will never get run, like calling a function after
you've done return 0; etc.
